### ISSUE TITLE
Dual monitor works but only recognizes the top bar, same as on single monitor

### ISSUE THREAD

**Issue by ghost** [arkeane/polybar_autohide#4]
Hi,

There's a first time for everything.

Running ArcoLinux i3, Ryzen 7 2700, RX-580 amdgpu, launching from i3. Autohide works as expected when mousing to the top bar, but does not when mousing to the bottom bar. I have the bottom bar only on primary. On my HP-8000 with Radeon 5450 running single monitor the result is the same - it only responds to mousing to the top bar.

Any log file(s)/configs that would help, I'll gladly pass along.

Thanks.

**Comment by arkeane** [comment]
I’m not actively developing polybar_autohide right now but i was thinking about rewriting it in the future with  more solid code and better integration with polybar. If you want to implement the dual bar function make a commit, i’ll gladly accept it.

**Comment by ghost** [comment]
I see. I don't code so it will simply wait. :)
