### ISSUE TITLE
Blinking interface

### ISSUE THREAD

**Issue by vanarok** [arkeane/polybar_autohide#5]
The program interface with the polybar hiding enabled starts blinking (updated) while working in it. 
My wm - i3, and compose picom.

**Comment by arkeane** [comment]
Can you be more specific about the blinking issues, does all the wm blink or just the bar, have you tried using it in different environments, is updated related to the latest version of autohide script?

**Comment by vanarok** [comment]
The problem in the java application is some kind of incompatibility with the polybar in hide mode, and not with this script, which uses the standard hide function.
